# config/routes.yaml
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Route de redirection par défaut
index:
  path: /
  controller: App\Controller\DefaultController::index
